import { Router } from "express";
import userRoutes from "./userRoute";
import accessControlRoutes from "./accessControlRoute";
import mobileSyncRoutes from "./mobileSyncRoutes";
import CoffeePurchaseRoutes from "./coffeePurchaseRouter";
import stationRoutes from "./stationRoute";
import daylotsRoutes from "./dayLotsRoute";
import harvestRouter from "./harvestRoute";
import dryingRoutes from "./dryingRoute";
import parchmentRoutes from "./parchmentRoute";
import parchmentTransportRoutes from "./parchmentTransportRoute";
import deliveryProcessingRouter from "./deliveryProcessingRoutes";
import untraceableCoffeeRoute from "./addUntraceableCoffee.route";
import cherryRoutes from "./cherryToRTCRoutes";
import inspectionsRouter from "./inspectionsRoutes";
import farmersRouter from "./farmersRoutes";
import groupsRouter from "./groupsRoutes";
import householdRouter from "./householdsRoute";
import trainingsRouter from "./trainingRoutes";
import attendanceRouter from "./attendanceRoutes";
import FarmerRouter from "./recentFarmerRoutes";
import UserAccessRouter from "./userAccessRoute";
import householdTreesRoutes from "./householdTreesRoutes";
import dashboardFMRoutes from "./dashboardFMRoute";
import translationsRouter from "./translationsRoute";
import evaluationRouter from "./evaluationsRoute";
import inspectionAnswersRoutes from "./inspectionAnswersRoute";
import registrationRoutes from "./registrationsRoute";

const router = Router();
router.use("/user", userRoutes);
router.use("/accessControl", accessControlRoutes);
router.use("/sync", mobileSyncRoutes);
router.use("/user", userRoutes);
router.use("/accessControl", accessControlRoutes);
router.use("/coffeePurchase", CoffeePurchaseRoutes);
router.use("/station", stationRoutes);
router.use("/lots", daylotsRoutes);
router.use("/harvests", harvestRouter);
router.use("/dryings", dryingRoutes);
router.use("/parchments", parchmentRoutes);
router.use("/parchmentTransport", parchmentTransportRoutes);
router.use("/loadedWeight", deliveryProcessingRouter);
router.use("/untraceableCoffee", untraceableCoffeeRoute);
router.use("/cherrytortc", cherryRoutes);
router.use("/inspections", inspectionsRouter);
router.use("/farmers", farmersRouter);
router.use("/groups", groupsRouter);
router.use("/households", householdRouter);
router.use("/trainings", trainingsRouter);
router.use("/attendance", attendanceRouter);
router.use("/user_registration", FarmerRouter);
router.use("/useraccess", UserAccessRouter);
router.use("/trees", householdTreesRoutes);
router.use("/dashboardApi", dashboardFMRoutes);
router.use("/translations", translationsRouter);
router.use("/evaluations", evaluationRouter);
router.use("/answers", inspectionAnswersRoutes);
router.use("/farmer_registrations", registrationRoutes);

export default router;
